In [2]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [2]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [7]:
print("pi to 9 significant digits = {:.9}".format(math.pi))

pi to 9 significant digits = 3.14159265


In [11]:
print("This is the log(9) = {}".format(math.log10(9)))

This is the log(9) = 0.9542425094393249


In [13]:
math.log(32,2)

5.0

In [16]:
# Import Syntax

import math as mt

#mt.pi

mt.log10(9)

0.9542425094393249

In [17]:
# Direct access Math module's variables

from math import *
print(pi, log(32,2), log10(9))

3.141592653589793 5.0 0.9542425094393249


In [ ]:
# Direct access as a drawback



In [3]:
# Submodules
import numpy
print("numpy.random is a", type(numpy.random))
print("numpy is a", type(numpy))
print("it contains names such as...", dir(numpy.random)[-15:])

#print("numpy contains names such as...", dir(numpy))

numpy.random is a <class 'module'>
numpy is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [4]:
import random

numpy.random.seed(30)
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([5, 5, 3, 4, 2, 4, 2, 2, 2, 4])

In [5]:
rolls.mean()

3.3

In [6]:
rolls.tolist()

[5, 5, 3, 4, 2, 4, 2, 2, 2, 4]

In [64]:
#help(numpy.random.seed(1))

type(numpy.random.seed(1))

NoneType

In [68]:
rolls + 10

array([15, 15, 13, 14, 12, 14, 12, 12, 12, 14])

In [69]:
# TypeError

[5, 5, 3, 4, 2, 4, 2, 2, 2, 4] + 10

TypeError: can only concatenate list (not "int") to list

In [7]:
# Designers of numpy arrays allows for adding number to each element in the array
rolls + 10

# Designers of List did not allow adding numbers
# [5, 5, 3, 4, 2, 4, 2, 2, 2, 4] + 10

# List != Numpy Array

array([15, 15, 13, 14, 12, 14, 12, 12, 12, 14])

In [73]:
rolls <= 3

array([False, False,  True, False,  True, False,  True,  True,  True,
       False])

In [9]:
xlist = [[1,2,3],[2,4,6]]
xlist

x = numpy.asarray(xlist)
print("xlist = {}\nx = \n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x = 
[[1 2 3]
 [2 4 6]]


In [10]:
x[1,-1]

6

In [12]:
# When does 1 + 1 not equal 2?

import tensorflow as tf
# Create two constants each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get
a + b

ModuleNotFoundError: No module named 'tensorflow'

In [13]:
type(graph)

NameError: name 'graph' is not defined